### ISSUE TITLE
Magic Strings (Avoid Magic Numbers/Strings)

### ISSUE THREAD

**Issue by jackhax** [XichengTong/SoftwareSupplyChainSecurity_HW1#1]
Hardcoding strings like API URLs makes the code less flexible. If the URL changes, it requires a manual search and replace. 
Potential fix: Use as config file to store APIs and other magic strings/magic numbers

https://github.com/XichengTong/SoftwareSupplyChainSecurity_HW1/blob/e32bee2352c30a83d3f281323abb1bd64c0ea378/main.py#L6

https://github.com/XichengTong/SoftwareSupplyChainSecurity_HW1/blob/e32bee2352c30a83d3f281323abb1bd64c0ea378/main.py#L23

For better security one can store API strings in env variables.

**Comment by XichengTong** [comment]
So i write a function to specifically give the  log_entry_url every time I need to use it and it is more easiler to change right now 
I use ` REKOR_API_URL = os.getenv("REKOR_API_URL", "https://rekor.sigstore.dev")` to make sure it avoid hardcoding the URL.
