### ISSUE TITLE
 Coding Standards Compliance (Inconsistent variable naming)

### ISSUE THREAD

**Issue by jackhax** [XichengTong/SoftwareSupplyChainSecurity_HW1#2]
The naming is inconsistent. You’re mixing snake_case with camelCase, which breaks uniformity.
Variables like log_entry_url, leaf_hash, etc., follow standard conventions, but terms like entryUUID don’t follow consistent naming styles.
Potential fix: Stick to one naming convention, preferably snake_case in Python.

https://github.com/XichengTong/SoftwareSupplyChainSecurity_HW1/blob/e32bee2352c30a83d3f281323abb1bd64c0ea378/main.py#L114

**Comment by XichengTong** [comment]
Changing all variables to snake_case
