### ISSUE TITLE
Implement fail fast

### ISSUE THREAD

**Issue by jackhax** [XichengTong/SoftwareSupplyChainSecurity_HW1#3]
Implement fail fast functionality, i.e check for the failure condition first and exit with an error instead of checking for a positive condition and continuing with the functionality.

https://github.com/XichengTong/SoftwareSupplyChainSecurity_HW1/blob/e32bee2352c30a83d3f281323abb1bd64c0ea378/main.py#L30

**Comment by XichengTong** [comment]
use `# Fail-fast check for failure condition to Implement fail fast functionality

        if response.status_code != 200:
            if debug:
                print(f"Failed to fetch log entry. Status code: {response.status_code}")
            return None`
