### ISSUE TITLE
Refactor Repeated API Request Logic

### ISSUE THREAD

**Issue by jackhax** [XichengTong/SoftwareSupplyChainSecurity_HW1#4]
Duplicated code increases maintenance complexity. When changes are needed (e.g., modifying how the API request is made), you have to modify it in multiple places, increasing the risk of missing one.

https://github.com/XichengTong/SoftwareSupplyChainSecurity_HW1/blob/e32bee2352c30a83d3f281323abb1bd64c0ea378/main.py#L23

https://github.com/XichengTong/SoftwareSupplyChainSecurity_HW1/blob/e32bee2352c30a83d3f281323abb1bd64c0ea378/main.py#L102

Create a helper function like fetch_from_rekor(api_url) to handle all API requests and reuse it throughout the code. This will reduce code duplication.

**Comment by XichengTong** [comment]
same as magic number issue #1 Solved with making a new function
